#!/usr/bin/env tclsh

package require Tk 8.5
package require tkdnd 2.6

wm title . "wrk2fit"
wm minsize . 120 120

set defaultText "WRK → FIT"

set fitFileTypes {{"FIT Workout Files" ".fit"} {"All Files" "*"}}
set wrkFileTypes {{"Wokrout Description Files" ".wrk"} {"All Files" "*"}}

ttk::label .dropLabel -text $defaultText \
    -anchor center -justify center -wraplength 120

grid rowconfigure    . 0 -weight 1
grid columnconfigure . 0 -weight 1

grid .dropLabel -row 0 -column 0 -sticky nesw -padx 5 -pady 5

tkdnd::drop_target register .dropLabel {DND_Files DND_Text}

proc onError {message} {
    global defaultText
    .dropLabel configure -background #dc322f -text $message
    after 1000 {
        .dropLabel configure -background {} -text $defaultText
    }
}

proc writeFile {path data} {
    # TODO: handle errors
    set fd [open $path {BINARY CREAT WRONLY}]
    puts -nonewline $fd $data
    close $fd
}

proc handleText {wrk} {
    # TODO
}

proc handleFile {wrkFile} {
    global fitFileTypes
    try {
        set fit [exec ./wrk2il < $wrkFile | ./il2fit]
        set path [tk_getSaveFile -filetypes $fitFileTypes]
        writeFile $path $fit
    } trap CHILDSTATUS {- opts} {
        onError "Bad WRK"
    }
}

bind .dropLabel <Double-1> {
    set filePath [tk_getOpenFile -filetypes $wrkFileTypes]
    if {$filePath ne ""} {
        handleFile $filePath
    } else {
        onError "No file selected"
    }
}

bind .dropLabel <<Drop:DND_Files>> {
    handleFile [lindex %D 0]
}

bind .dropLabel <<Drop:DND_Text>> {
    handleText %D
}
