# -*- mode: makefile -*-

.PHONY: configure distclean

configure:
	mirage configure --unix --net=socket

distclean: clean
	rm -f	\
		Makefile	\
		key_gen.ml	\
		log	\
		main.ml	\
		mir-wrked.xen	\
		wrked.xe	\
		wrked.xl	\
		wrked.xl.in	\
		wrked_libvirt.xml
